---
- name: airflow deploy apply 
  hosts: 
    - 158.247.252.37
  become: yes
  vars:
    airflow_app_name: airflow
    airflow_storage_name: airflow-storage-class
    airflow_replicas: 2
    airflow_image_name: apache/airflow:latest


  tasks:
    - name: Create StorageClass for airflow
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: "{{ airflow_storage_name }}"
          provisioner: kubernetes.io/no-provisioner
          volumeBindingMode: WaitForFirstConsumer


    - name: Deploy airflow StatefulSet
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            name: "{{ airflow_app_name }}"
          spec:
            serviceName: "{{ airflow_app_name }}"
            replicas: "{{ airflow_replicas }}"
            selector:
              matchLabels:
                app: "{{ airflow_app_name }}"
            template:
              metadata:
                labels:
                  app: "{{ airflow_app_name }}"
              spec:
                containers:
                - name: "{{ airflow_app_name }}"
                  image: "{{ airflow_image_name }}"
                  ports:
                  - containerPort: 11100
            volumeClaimTemplates:
            - metadata:
                name: airflow-storage
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: "{{ airflow_storage_name }}"


    - name: Expose the StatefulSet as a service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: airflow-service
          spec:
            selector:
              app: "{{ airflow_app_name }}"
            ports:
              - protocol: TCP
                port: 11100
                targetPort: 11100
            type: LoadBalancer