- name: flask deploy apply 
  hosts: master
  become: true
  vars:
    flask_app_name: flask
    flask_replicas: 3
    flask_image_name: flask:latest

  tasks:
    - name: Create or update Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        definition: 
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: flask-deployment
            labels:
              app: {{ flask_app_name }}
          spec:
            replicas: {{ flask_replicas }}
            selector:
              matchLabels:
                app: {{ flask_app_name }}
            template:
              metadata:
                labels:
                  app: {{ flask_app_name }}
              spec:
                containers:
                - name: {{ flask_app_name }}
                  image: {{ flask_image_name }}
                  ports:
                  - containerPort: 11000


    - name: Expose the deployment as a service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: flask-service
          spec:
            selector:
              app: {{ flask_app_name }}
            ports:
              - protocol: TCP
                port: 11000
                targetPort: 11000


    - name: Set Ingress for Flask
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: flask-ingress
          spec:
            rules:
            - http:
                paths:
                - path: /flask
                  pathType: Prefix
                  backend:
                    service:
                      name: flask-app-service
                      port:
                        number: 80