---
- name: hive deploy apply 
  hosts: master
  become: yes
  vars:
    hive_app_name: hive
    hive_replicas: 2
    hive_image_name: bigtop:latest

  tasks:
    - name: Create or update Kubernetes Deployment
      k8s:
        state: present
        definition: 
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ hive_app_name }}-deployment"
            labels:
              app: "{{ hive_app_name }}"
          spec:
            replicas: "{{ hive_replicas }}"
            selector:
              matchLabels:
                app: "{{ hive_app_name }}"
            template:
              metadata:
                labels:
                  app: "{{ hive_app_name }}"
              spec:
                containers:
                - name: "{{ hive_app_name }}"
                  image: "{{ hive_image_name }}"
                  ports:
                  - containerPort: 10300

    - name: Expose the deployment as a service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ hive_app_name }}"
          spec:
            selector:
              app: "{{ hive_app_name }}"
            ports:
              - protocol: TCP
                port: 10300
                targetPort: 10300
            type: ClusterIP