---
- name: nginx deploy apply 
  hosts: master
  become: yes
  vars:
    nginx_app_name: nginx
    nginx_replicas: 2
    nginx_image_name: nginx:latest

  tasks:
    - name: Create or update Kubernetes Deployment
      k8s:
        state: present
        definition: 
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            labels:
              app: "{{ nginx_app_name }}"
          spec:
            replicas: "{{ nginx_replicas }}"
            selector:
              matchLabels:
                app: "{{ nginx_app_name }}"
            template:
              metadata:
                labels:
                  app: "{{ nginx_app_name }}"
              spec:
                containers:
                - name: "{{ nginx_app_name }}"
                  image: "{{ nginx_image_name }}"
                  ports:
                  - containerPort: 80

    - name: Expose the deployment as a service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ nginx_app_name }}"
          spec:
            selector:
              app: "{{ nginx_app_name }}"
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
            type: LoadBalancer