- name: Kubernetes Install
  hosts: all
  become: true
  vars:
    Kubelet_version: 1.30
    Kubeadm_version: 1.30
    Kubectl_version: 1.30

  tasks:
    # 쿠버네티스 파트 시작
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present
      when: ansible_os_family == "Debian"

    - name: Download gpg
      apt_key:
        url: https://apt.kubernetes.io/apt/doc/apt-key.gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Kubernetes repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes jammy main

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Kubernetes components
      apt:
        name:
          - "kubelet={{ kubelet_version }}"
          - "kubeadm={{ kubeadm_version }}"
          - "kubectl={{ kubectl_version }}"
        state: present
        allow_downgrade: yes


- name: Kubernetes init
  hosts: master
  become: true
  vars:
    kubernetes_version: "1.30"
    Master_node: 158.247.252.37

  tasks:
    - name: Check Kubernetes init excuted
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf_status

    - name: init Kubernetes master node
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-cert-extra-sans="{{ Master_node }}"
      register: kubeadm_init_output
      when: not kubelet_conf_status.stat.exists

    - name: Set kubeconfig for root
      shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
      when: not kubelet_conf_status.stat.exists

    - name: Save join command to file
      local_action:
        module: copy
        content: "{{ kubeadm_init_output.stdout | regex_search('kubeadm join.*') }}"
        dest: ./join_command.sh
      when: not kubelet_conf_status.stat.exists

    - name: Apply Flannel CNI plugin
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      when: not kubelet_conf_status.stat.exists


- name: Kubernetes join
  hosts: worker
  become: true
  vars:
    kubernetes_version: "1.30"
    Master_node: 158.247.252.37

  tasks:
    - name: Check Kubernetes join executed
      stat:
        path: /var/lib/kubelet/config.yaml
      register: kubelet_conf_yaml_status

    - name: Join Kubernetes worker node
      shell: "bash ./join_command.sh"
      when: not kubelet_conf_yaml_status.stat.exists