---
- name: spark deploy apply 
  hosts: master
  become: yes
  vars:
    spark_app_name: spark
    spark_replicas: 2
    spark_image_name: bigtop:latest

  tasks:
    - name: Create or update Kubernetes Deployment
      k8s:
        state: present
        definition: 
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ spark_app_name }}-deployment"
            labels:
              app: "{{ spark_app_name }}"
          spec:
            replicas: "{{ spark_replicas }}"
            selector:
              matchLabels:
                app: "{{ spark_app_name }}"
            template:
              metadata:
                labels:
                  app: "{{ spark_app_name }}"
              spec:
                containers:
                - name: "{{ spark_app_name }}"
                  image: "{{ spark_image_name }}"
                  ports:
                  - containerPort: 10000

    - name: Expose the deployment as a service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ spark_app_name }}"
          spec:
            selector:
              app: "{{ spark_app_name }}"
            ports:
              - protocol: TCP
                port: 10000
                targetPort: 10000
            type: ClusterIP